services:
  - type: web
    name: interviewtrainer-backend
    env: node
    plan: free
    buildCommand: |
      # Install system dependencies
      apt-get update
      apt-get install -y build-essential g++ python3 python3-pip default-jdk
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
